# Introducción a Numpy

Numerical Python Library


> NumPy es una biblioteca de Python que da soporte para crear vectores y matrices grandes multidimensionales, junto con una gran colección de funciones matemáticas de alto nivel para operar con ellas.

Sitio oficial: [numpy.org](https://numpy.org)
Documentación oficial: [numpy.org/doc/stable/](https://numpy.org/doc/stable/)

In [1]:
import numpy as np

## Indexing

In [2]:
# Para acceder a un elemento en un array unidimensional, simplemente utilizamos su índice
a = np.array([1, 3, 5, 7])
a[2]

5

In [3]:
# Para arrays multidimensionales, debemos utilizar su índice completo
a = np.array([[1, 2 ], [3, 4], [5, 6]])
print(a)
print(a[2, 1])  # output: 6

[[1 2]
 [3 4]
 [5 6]]
6


## Slicing

Slicing es una forma de crear un subarray basado en el array original.

Slicing tiene el siguiente tres argumentos separados por `:`
- el primero hace referencia al índice del elemento inicial.
- el segundo hace referencia al índice del último elemento, pero no lo incluye.
- el tercero hace referencia al salto.

Si algunos de estos argumentos se omiten, toman su valor por defecto (default)

Ejemplo:
```python
foo = [a, b, c, d, e, f, g, h, i, j, q]
foo[0:3:1]  # Output [a, b, c]
foo[2:7:1]  # Output [c, d, e, f, g]
foo[1:10:2]  # Output [b, d, f, h, j]

In [4]:
# Para arrays unidimensionales, slicing funciona igual que para las listas de Python.
a = np.array([0, 1, 2, 3, 4, 5])
print(a[:3])

[0 1 2]


In [5]:
# Para arrays bidimensionales, slicing nos permite dos argumentos, el primero filtrará las filas, y el segundo filtrará las columnas.
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [6]:
# Primero, trabajemos con un solo argumento, por ejemplo: a[:2]
print(a[:2])  # obtenemos la fila 0 y la fila 1

[[1 2 3 4]
 [5 6 7 8]]


In [7]:
# A continuación, agregamos el segundo argumento, por ejemplo a[:2, 1:3]
print(a[:2, 1:3])  # Obtenemos las filas 0 y 1, pero solo los elementos de la segunda y tercera columna

[[2 3]
 [6 7]]
