# Introducción a Numpy

Numerical Python Library


> NumPy es una biblioteca de Python que da soporte para crear vectores y matrices grandes multidimensionales, junto con una gran colección de funciones matemáticas de alto nivel para operar con ellas.

[Sitio oficial: numpy.org](https://numpy.org) | [Documentación oficial](https://numpy.org/doc/stable/)

In [2]:
import numpy as np

## Creación de array

## array()

Con NumPy podemos crear un array desde una lista de Python. En este caso crearemos un array de una dimensión

In [3]:
a= np.array([1, 2, 3])  # Array de una dimensión
a, a.ndim

(array([1, 2, 3]), 1)

Pero si le damos como argumento una lista de listas, entonces obtenemos un array de dos dimensions.

In [4]:
b= np.array([(1, 2, 3), (7, 8, 9)])  # Array de dos dimensiones
b, b.ndim

(array([[1, 2, 3],
        [7, 8, 9]]),
 2)

Podemos saber el largo de cada dimensión llamando al atributo shape que nos retornará un tupla

In [5]:
b.shape

(2, 3)

También podemos saber el tipo de los elementos de un array

In [6]:
b.dtype

dtype('int64')

Podemos utilizar números decimales (flotantes) también

In [7]:
c = np.array([2.5, 4, 6.5, 11,2])
c, c.dtype.name

(array([ 2.5,  4. ,  6.5, 11. ,  2. ]), 'float64')

Notemos que NumPy automáticamente convirtió los números enteros en flotantes. Entonces al número 4 (int64) lo convirtió en 4. (float64)

Numpy intentará brindarnos el mejor formato de tipo de datos posible para mantener sus tipos de datos homogéneos.

Esto significa que todos los elementos en la matriz serán del mismo tipo.

## zeros() ones()

NunPy nos ofrece varias funciones para crear arrays con valores iniciales, como ceros o unos.

Crea un array de una dimensión con 10 elementos iguales a 0

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Crea un array de dos dimensiones con tres filas y 5 columnas, donde todos sus elementos son igual a 1

In [9]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## random.rand() arange() linspaces()

Podemos generar un array con números aleatorios

Genera un array de 3 filas y 5 columnas con números aleatorios (entre 0 y 0,99...)

In [10]:
np.random.rand(3,5)

array([[0.60773591, 0.51560272, 0.12206737, 0.49088764, 0.34989352],
       [0.46067323, 0.76331946, 0.68695583, 0.88883517, 0.79018194],
       [0.06472089, 0.62616237, 0.18314382, 0.36218766, 0.27697346]])

Si necesitamos números aleatorios entre 0 y 100 (no inclusive), simplemente los multiplicamos y obtenemos lo que deseamos

In [11]:
np.random.rand(4, 5) * 100  # Array de 4x5 con valores entre 0 y 100 (no inclusive)

array([[62.99150119, 82.15080422,  9.09954834, 72.12023838, 92.26531449],
       [72.27431263, 49.10748768, 55.81863982, 24.22831793, 61.87097195],
       [79.1929538 , 77.13267345, 62.32165628, 72.37935547, 63.00867378],
       [75.31874745, 46.88777927, 22.31569191, 90.25826099, 59.63879527]])

Pero también tenemos la función arange() para crear secuencias de números aleatorios.

En esta función, el primer argumento será el valor inicial del rango, el segundo el valor final (no incluído), y el tercero la diferencia entre números consecutivos

In [12]:
f= np.arange(10, 50, 2)  # Crear un array de números pares entre 10 (incluído) y 50 (no incluído)
f.ndim, f

(1,
 array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
        44, 46, 48]))

Si deseamos generar una secuencia de números flotantes, podemos usar la función linspace().

En esta función, el tercero no es la diferencia entre números consecutivos, sino que es el total de elementos que deso generar.

In [13]:
g = np.linspace(0, 10, 15)  # Genera un array con 15 números decimales entre 0 (incluído) y 10 (no incluído)
g.ndim, g

(1,
 array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
         3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
         7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ]))