# Statistical Computing, Probability & Random Sampling with NumPy


## 1. Importación básica

In [1]:
import numpy as np

## 2. Cálculo estadístico con NumPy

In [2]:
data = np.array([12, 15, 20, 22, 21, 18, 19])

In [3]:
np.mean(data)

18.142857142857142

In [4]:
np.median(data)

19.0

In [5]:
np.var(data)

10.693877551020408

In [6]:
np.std(data)

3.270149469217028

In [7]:
np.min(data), np.max(data)

(12, 22)

### Ejemplo aplicado

In [8]:
incomes = np.array([350, 420, 290, 510, 480, 610, 430])

In [9]:
np.mean(incomes)

441.42857142857144

In [10]:
np.std(incomes)

97.45747371891737

## 3. Probabilidad y generación de distribuciones aleatorias

In [11]:
np.random.rand(5)

array([0.31441125, 0.94338781, 0.23071539, 0.53051187, 0.44900459])

In [12]:
np.random.randint(0, 100, size=5)

array([13, 50, 61, 29, 18])

## 4. Distribuciones comunes

In [13]:
np.random.uniform(low=0, high=10, size=10)

array([1.53089862, 7.3562653 , 2.37519536, 1.04416155, 9.32546303,
       7.35853023, 4.74138488, 7.89779583, 3.83282837, 1.49568509])

In [14]:
np.random.normal(loc=0, scale=1, size=10)

array([ 0.8864004 , -0.14215098, -0.65266429,  2.15325483,  0.05147048,
       -0.213016  ,  1.31062006,  2.43409318,  0.38788576,  1.2190405 ])

In [15]:
np.random.binomial(n=10, p=0.5, size=10)

array([6, 4, 4, 7, 6, 5, 3, 7, 4, 8])

In [16]:
np.random.poisson(lam=3, size=10)

array([0, 4, 4, 4, 4, 3, 4, 5, 2, 0])

## 5. Muestreo aleatorio

In [17]:
productos = np.array(['A', 'B', 'C', 'D', 'E'])

In [18]:
np.random.choice(productos, size=3, replace=False)

array(['B', 'E', 'C'], dtype='<U1')

## 6. Ejemplo integrador

In [19]:
ventas = np.random.normal(loc=200, scale=30, size=30)
ventas

array([176.16027947, 171.07662012, 176.09398078, 182.02365459,
       188.68800498, 147.43280458, 157.80531321, 222.8080942 ,
       218.59666446, 266.29325216, 205.60920988, 210.70929534,
       212.38779735, 266.23863967, 214.54777667, 165.10500916,
       199.53675699, 198.16953482, 213.66879625, 146.18752946,
       233.04782301, 171.92978752, 229.70342463, 204.86916374,
       173.6279349 , 199.72234828, 220.95218963, 206.18706062,
       176.82659731, 263.42308501])

In [20]:
np.mean(ventas)

200.64761429309513

In [21]:
np.std(ventas)

31.591422545713016

In [22]:
np.max(ventas)

266.29325216472233