# Introducción a Numpy

Numerical Python Library


> NumPy es una biblioteca de Python que da soporte para crear vectores y matrices grandes multidimensionales, junto con una gran colección de funciones matemáticas de alto nivel para operar con ellas.

[Sitio oficial: numpy.org](https://numpy.org) | [Documentación oficial](https://numpy.org/doc/stable/)

In [1]:
import numpy as np

## Creación de array

## array()

In [2]:
# Con NumPy podemos crear un array desde una lista de Python. En este caso crearemos un array de una dimensión
a= np.array([1, 2, 3])  # Array de una dimensión
a, a.ndim

(array([1, 2, 3]), 1)

In [3]:
# Pero si le damos como argumento una lista de listas, entonces obtenemos un array de dos dimensions.
b= np.array([(1, 2, 3), (7, 8, 9)])  # Array de dos dimensiones
b, b.ndim

(array([[1, 2, 3],
        [7, 8, 9]]),
 2)

In [4]:
# Podemos saber el largo de cada dimensión llamando al atributo shape que nos retornará un tupla
b.shape

(2, 3)

In [5]:
# También podemos saber el tipo de los elementos de un array
b.dtype

dtype('int64')

In [6]:
# Podemos utilizar números decimales (flotantes) también
c = np.array([2.5, 4, 6.5, 11,2])
c, c.dtype.name

(array([ 2.5,  4. ,  6.5, 11. ,  2. ]), 'float64')

In [7]:
# Notemos que NumPy automáticamente convirtió los números enteros en flotantes. Entonces al número 4 (int64) lo convirtió en 4. (float64)
# Numpy intentará brindarnos el mejor formato de tipo de datos posible para mantener sus tipos de datos homogéneos. 
# Esto significa que todos los elementos en la matriz serán del mismo tipo.

## zeros() ones()

NunPy nos ofrece varias funciones para crear arrays con valores iniciales, como ceros o unos.

In [8]:
# Crearemos dos array, el primero con ceros (0) como valores iniciales, y el segundo con unos (1).
# El argumento será una lista con los valores de la dimensión del array que se creará
d = np.zeros(10)  # Crea un array de una dimensión con 10 elementos iguales a 0 
e = np.ones((3, 5))  # Crea un array de dos dimensiones con tres filas y 5 columnas, donde todos sus elementos son igual a 1 
d, e

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

## random.rand() arange() linspaces()

In [9]:
# Podemos generar un array con números aleatorios 
np.random.rand(3,5)  # Genera un array de 3 filas y 5 columnas con números aleatorios (entre 0 y 0,99...)

array([[0.39848751, 0.66275995, 0.97634895, 0.50802307, 0.83623936],
       [0.01271629, 0.61388218, 0.12405496, 0.54064821, 0.62487962],
       [0.69171288, 0.88581418, 0.24829207, 0.3945448 , 0.55178511]])

In [10]:
# Si necesitamos números aleatorios entre 0 y 100 (no inclusive), simplemente los multiplicamos y obtenemos lo que deseamos 
np.random.rand(4, 5) * 100  # Array de 4x5 con valores entre 0 y 100 (no inclusive)

array([[81.67074971, 98.43133934, 86.16181338, 56.56031095, 60.38119711],
       [28.90317958, 74.50609177, 54.48242804,  6.6013586 , 17.19876238],
       [52.1896721 , 64.61156542, 44.14047116, 48.68866706, 73.49319661],
       [82.63800645, 44.04792721,  5.15242461, 12.20626149,  8.05209394]])

In [11]:
# Pero también tenemos la función arange() para crear secuencias de números aleatorios.
# En esta función, el primer argumento será el valor inicial del rango, el segundo el valor final (no incluído), y el tercero la diferencia entre números consecutivos
f= np.arange(10, 50, 2)  # Crear un array de números pares entre 10 (incluído) y 50 (no incluído) 
f, f.ndim

(array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
        44, 46, 48]),
 1)

In [12]:
# Si deseamos generar una secuencia de números flotantes, podemos usar la función linspace().
# En esta función, el tercero no es la diferencia entre números consecutivos, sino que es el total de elementos que deso generar.
g = np.linspace(0, 10, 15)  # Genera un array con 15 números decimales entre 0 (incluído) y 10 (no incluído)
g, g.ndim

(array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
         3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
         7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ]),
 1)