# Statistical Computing, Probability & Random Sampling with NumPy


## 1. Importación básica

In [1]:
import numpy as np

## 2. Cálculo estadístico con NumPy

In [2]:
data = np.array([12, 15, 20, 22, 21, 18, 19])

In [3]:
np.mean(data)

18.142857142857142

In [4]:
np.median(data)

19.0

In [5]:
np.var(data)

10.693877551020408

In [6]:
np.std(data)

3.270149469217028

In [7]:
np.min(data), np.max(data)

(12, 22)

### Ejemplo aplicado

In [8]:
incomes = np.array([350, 420, 290, 510, 480, 610, 430])

In [9]:
np.mean(incomes)

441.42857142857144

In [10]:
np.std(incomes)

97.45747371891737

## 3. Probabilidad y generación de distribuciones aleatorias

In [11]:
np.random.rand(5)

array([0.75231821, 0.30304415, 0.70472661, 0.09222419, 0.65121237])

In [12]:
np.random.randint(0, 100, size=5)

array([80,  7, 79, 38, 53])

## 4. Distribuciones comunes

In [13]:
np.random.uniform(low=0, high=10, size=10)

array([6.88110963, 3.46352126, 1.15378143, 2.68943325, 7.90686534,
       3.24485333, 2.96321756, 3.19488816, 6.08557678, 9.89107814])

In [14]:
np.random.normal(loc=0, scale=1, size=10)

array([ 0.22371204,  1.05606043, -0.38101987, -1.37559577,  2.42977266,
       -0.24079963,  0.16955778, -0.28958245,  0.17777353, -0.5035206 ])

In [15]:
np.random.binomial(n=10, p=0.5, size=10)

array([8, 5, 7, 4, 3, 7, 4, 7, 7, 3])

In [16]:
np.random.poisson(lam=3, size=10)

array([3, 2, 2, 2, 1, 4, 6, 2, 4, 5])

## 5. Muestreo aleatorio

In [17]:
productos = np.array(['A', 'B', 'C', 'D', 'E'])

In [18]:
np.random.choice(productos, size=3, replace=False)

array(['D', 'E', 'C'], dtype='<U1')

## 6. Ejemplo integrador

In [19]:
ventas = np.random.normal(loc=200, scale=30, size=30)
ventas

array([199.66444892, 188.98600974, 218.13906252, 171.9587346 ,
       238.04607728, 170.91502302, 149.4753035 , 177.35484195,
       158.46556   , 219.96784857, 251.02468992, 247.35439337,
       149.89883645, 182.16688158, 178.872661  , 179.83251011,
       190.03566424, 227.44570645, 202.25492227, 183.96653723,
       230.81657969, 221.36854713, 161.15651996, 205.92221267,
       196.82315541, 199.16798513, 204.65053503, 191.61869967,
       197.69266792, 184.04414249])

In [20]:
np.mean(ventas)

195.96955859448798

In [21]:
np.std(ventas)

26.57497683418693

In [22]:
np.max(ventas)

251.02468992180798